### PR TITLE
Improve websocket connection

### LINKED ISSUE #416: Error when closing the web interface
If I'm working with the web interface and then close the browser window, the following error is shown in kytos:
```
Traceback (most recent call last):
  File "/home/renan/testes/asd/lib/python3.6/site-packages/werkzeug/serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "/home/renan/testes/asd/lib/python3.6/site-packages/werkzeug/serving.py", line 197, in execute
    application_iter = app(environ, start_response)
  File "/home/renan/testes/asd/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/renan/testes/asd/lib/python3.6/site-packages/flask_socketio/__init__.py", line 42, in __call__
    start_response)
  File "/home/renan/testes/asd/lib/python3.6/site-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/renan/testes/asd/lib/python3.6/site-packages/socketio/server.py", line 353, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/renan/testes/asd/lib/python3.6/site-packages/engineio/server.py", line 268, in handle_request
    self.disconnect(sid)
  File "/home/renan/testes/asd/lib/python3.6/site-packages/engineio/server.py", line 202, in disconnect
    self._get_socket(sid).close()
  File "/home/renan/testes/asd/lib/python3.6/site-packages/engineio/server.py", line 411, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
```

### PR DESCRIPTION
**Pull request by macartur**
This commit will improve the websocket to use gevent + gevent-websocket to avoid
the error KeyError: 'Session is disconnected'
Fix #416

### CODE REVIEW

**Comment by cemsbr** [comment]
I tried to use eventlet, but it was not logging messages sent outside the eventlet. Did you check whether all messages are being sent?

Besides, I'm working on a huge logging refactoring removing the websocket buffer and I think we should wait my PR to discuss a possible merge (in the next day or two).

**Review by cemsbr — CHANGES_REQUESTED** [review]
My comments are in the conversation.

**Comment by beraldoleal** [comment]
Since that @cemsbr is working on this I will wait until his PR. Also I noticed two more dependencies. We have to try to avoid adding more dependencies.

**Comment by cemsbr** [comment]
To have WebSockets instead of long polling, we must use gevent (and gevent-websocket) or eventlet in flask-socketio. Both lead to strange behavior when logging from outside flask. This is because they make flask run asynchronously, and our code is not async. I haven't found a simple solution for that.

I suggest keeping the long-polling approach until we change our architecture. Performance is not an issue right now.

**Comment by beraldoleal** [comment]
@macartur ?

**Comment by diraol** [comment]
@cemsbr this PR should be considered even after your PR about this?

**Comment by cemsbr** [comment]
I'm closing this in favor of #451, as discussed with @macartur.

**Pull request closed without merging**
