### PR TITLE
Fix 338 - Warning message for no napps dir

### PR DESCRIPTION
**Pull request by diraol**

### CODE REVIEW

**Comment by diraol** [comment]
@beraldoleal working now!

**Review by cemsbr — APPROVED** [review]
Maybe a shorter log message would be better, but that's fine.

**Comment by beraldoleal** [comment]
@diraol we are doing a huge refactoring on this. So I will hold this for a moment.

**Comment by beraldoleal** [comment]
Thanks @diraol but since that we did a huge refactoring we already fixed this.

**Pull request closed without merging**
