### PR TITLE
Make KytosNApp().__event an instance attribute

### LINKED ISSUE #532: __event.set() causes re-enabled NApps's loops to fail.
When a NApp is disabled, a call to `self.__event.set()` is executed. If it is enabled again without restarting the controller, `self.__event.is_set()` keeps returning `True`, preventing the `execute` method to loop when intended.

A call to `self.__event.clear()` is needed prior to execution to fix this.

### PR DESCRIPTION
**Pull request by renanrodrigo**
Fix #532

### CODE REVIEW

**Review by diraol — COMMENTED** [review]
@renanrodrigo I'm not absolutely sure that this is the best approach.

First, because I would expect that when a NApp is unloaded the NApp instance should be 'destroyed', then, when it is loaded again it should be a new instance. Therefore, it would behave as the first NApp load.

From the behavior you described, it looks like the NApp instance is being reused, which shouldn't be the case. So, I think we have do to a better investigation on why this is happening in order to really understand where the problem is. Specially because this can bring other undesired consequences.

Secondly, If we need to call `self.__event.clear()`, I would think on calling it on the `__init__()` method. It makes more sense to me to call it over there.

Btw, a fast look at the source coude made me think that this unexpected behavior may be happening because we are dealing with a Class attribute (`__event`) instead of an Instance attribute. If this is the reason, then we should instantiate `__event` on the `__init__()`.
I would do some tests to see if this won't bring problems related to our threading model while accessing the `__event` attribute.

Doing so, we probably won't need to call `__event.clear()`.

**Comment by renanrodrigo** [comment]
Right, @diraol !
I'm testing thins and updating ASAP.

**Review by diraol — CHANGES_REQUESTED** [review]
@renanrodrigo tested my suggestion and it seemed to work ok (add `self.__event = Event()` on the `__init__` instead of as class attribute. So, he will make the change proposed on my previous comment.

**Comment by renanrodrigo** [comment]
As discussed above, I changed the commit to apply the most reasonable solution.

**Review by diraol — APPROVED** [review]

**Pull request merged**
