### PR TITLE
hidden ip webshot

### PR DESCRIPTION
**Pull request by valessiobrito**
fix screenshot

### CODE REVIEW

**Review by hdiogenes — APPROVED** [review]
Approved. For the next screenshots, a tip: instead of putting a random IP address (which belongs to some random organization), there's a specific subnet reserved just to be used in examples and documentation – 192.0.2.0/24.

**Comment by beraldoleal** [comment]
@valessiobrito please rebase this PR, is out-of-date.

**Comment by beraldoleal** [comment]
@hdiogenes @valessiobrito tests...

**Comment by hdiogenes** [comment]
I think the tests will be fixed after the next rebase, @valessiobrito.

**Comment by beraldoleal** [comment]
@valessiobrito @hdiogenes come on guys... lets include this small PR! :/

**Pull request merged**
