### PR TITLE
Sets the appropriate permission to the napps folder.

### LINKED ISSUE #349: Napps installed module directory permission bug
similar to:
https://github.com/kytos/kytos-utils/issues/77
Installed Napps module directory is being created with wrong permissions, and makes the napp invisible to regular users.

### PR DESCRIPTION
**Pull request by erickvermot**
closes #349

### CODE REVIEW

**Comment by diraol** [comment]
@erickvermot Shouldn't we do this on all directories under the "napps_dir" ? (`kytos`, `kytos/napps`, `kytos/napps/.installed`, `kytos/napps/<author>`, `kytos/napps/<author>/<napp>`?

**Comment by erickvermot** [comment]
@diraol, as I remember the _create_module function creates the parent directories with the correct permissions. The only folder that presents the problem is the one created using mkdtemp and later copied preserving the original 700 mode set by mkdtemp: The ``<napp>`` folder.

**Comment by erickvermot** [comment]
* The ``<napp>`` folder.

**Review by diraol — APPROVED** [review]
Got it! =)

**Pull request merged**
