### PR TITLE
Move flow.py to the of_core NApp

### LINKED ISSUE #431: Move 'flow.py' to appropriate place
The module `flow.py` in `kytos/core` is in an incorrect place. As it deals only with OpenFlow related objects, it should be in `python-openflow` or in a NApp.
A discussion with @beraldoleal and @diraol brought that it should be moved to the `of_core` NApp.
Prior to any change, it's needed to check where in the code those flow-related classes are being used.

### PR DESCRIPTION
**Pull request by renanrodrigo**
Fix #431

Depends on kytos/kytos-napps#278

### CODE REVIEW

**Comment by beraldoleal** [comment]
@renanrodrigo tests ? @diraol @cemsbr please... review here...

**Comment by renanrodrigo** [comment]
@beraldo not sure unittests will pass because of the dependency on the other PR.

**Review by diraol — APPROVED** [review]

**Review by cemsbr — APPROVED** [review]

**Review by cemsbr — CHANGES_REQUESTED** [review]
Please, rebase and apply the changes to where this file is now.

**Comment by renanrodrigo** [comment]
Done.

**Review by cemsbr — APPROVED** [review]

**Pull request merged**
